hand_description:
  clam_arm:
    hand_frame: gripper_roll_link
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: l_gripper_pincher
    hand_group_name: clam_end_effector
    arm_group_name: clam_arm
    hand_database_name: WILLOW_GRIPPER_2010
    hand_joints: [l_gripper_aft_link,r_gripper_aft_link,l_gripper_fwd_link,r_gripper_fwd_link,l_gripper_pincher,r_gripper_pincher]
    hand_touch_links: [l_gripper_pincher,r_gripper_pincher]
    hand_fingertip_links: [l_gripper_pincher,r_gripper_pincher]
    hand_approach_direction: [1.0,0.0,0.0]