multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: Arm
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_roll_joint
      - elbow_pitch_joint
      - wrist_roll_joint
      - wrist_pitch_joint
  - name: Gripper
    joints:
      - gripper_roll_joint
      - gripper_grip_joint
  - name: clam_arm
    base_link: base_link
    tip_link: gripper_grip_link
default_collision_operations:
  - object1: base_link
    object2: shoulder_pan_link
    operation: disable  # Adjacent in collision
  - object1: shoulder_pan_link
    object2: shoulder_pitch_link
    operation: disable  # Adjacent in collision
  - object1: shoulder_pitch_link
    object2: elbow_roll_link
    operation: disable  # Adjacent in collision
  - object1: elbow_roll_link
    object2: elbow_pitch_link
    operation: disable  # Adjacent in collision
  - object1: elbow_pitch_link
    object2: wrist_roll_link
    operation: disable  # Adjacent in collision
  - object1: wrist_roll_link
    object2: wrist_pitch_link
    operation: disable  # Adjacent in collision
  - object1: wrist_pitch_link
    object2: gripper_roll_link
    operation: disable  # Adjacent in collision
  - object1: gripper_roll_link
    object2: gripper_grip_link
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: elbow_pitch_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: elbow_roll_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: gripper_grip_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: gripper_roll_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: shoulder_pitch_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: wrist_pitch_link
    operation: disable  # Never in collision
  - object1: base_link
    object2: wrist_roll_link
    operation: disable  # Never in collision
  - object1: elbow_pitch_link
    object2: gripper_grip_link
    operation: disable  # Never in collision
  - object1: elbow_pitch_link
    object2: gripper_roll_link
    operation: disable  # Never in collision
  - object1: elbow_pitch_link
    object2: shoulder_pan_link
    operation: disable  # Never in collision
  - object1: elbow_pitch_link
    object2: shoulder_pitch_link
    operation: disable  # Never in collision
  - object1: elbow_pitch_link
    object2: wrist_pitch_link
    operation: disable  # Never in collision
  - object1: elbow_roll_link
    object2: gripper_grip_link
    operation: disable  # Never in collision
  - object1: elbow_roll_link
    object2: gripper_roll_link
    operation: disable  # Never in collision
  - object1: elbow_roll_link
    object2: shoulder_pan_link
    operation: disable  # Never in collision
  - object1: elbow_roll_link
    object2: wrist_pitch_link
    operation: disable  # Never in collision
  - object1: elbow_roll_link
    object2: wrist_roll_link
    operation: disable  # Never in collision
  - object1: gripper_grip_link
    object2: shoulder_pan_link
    operation: disable  # Never in collision
  - object1: gripper_grip_link
    object2: shoulder_pitch_link
    operation: disable  # Never in collision
  - object1: gripper_grip_link
    object2: wrist_pitch_link
    operation: disable  # Never in collision
  - object1: gripper_grip_link
    object2: wrist_roll_link
    operation: disable  # Never in collision
  - object1: gripper_roll_link
    object2: shoulder_pan_link
    operation: disable  # Never in collision
  - object1: gripper_roll_link
    object2: shoulder_pitch_link
    operation: disable  # Never in collision
  - object1: gripper_roll_link
    object2: wrist_roll_link
    operation: disable  # Never in collision
  - object1: shoulder_pan_link
    object2: wrist_pitch_link
    operation: disable  # Never in collision
  - object1: shoulder_pan_link
    object2: wrist_roll_link
    operation: disable  # Never in collision
  - object1: shoulder_pitch_link
    object2: wrist_pitch_link
    operation: disable  # Never in collision
  - object1: shoulder_pitch_link
    object2: wrist_roll_link
    operation: disable  # Never in collision