joint_limits:
  shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder_pitch_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  elbow_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  elbow_pitch_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_pitch_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  gripper_roll_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  gripper_grip_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false